// <auto-generated />
namespace NoshSpot.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MakeCategoryToRestaurantOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeCategoryToRestaurantOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201609142054215_MakeCategoryToRestaurantOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
